<!-- Vendor jQuery-->
<script type="text/javascript" src="/libs/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/libs/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/libs/animate/wow.min.js"></script>
<script type="text/javascript" src="/libs/jquery.mmenu.all/jquery.mmenu.all.min.js"></script>
<script type="text/javascript" src="/libs/countdown/jquery.countdown.min.js"></script>
<script type="text/javascript" src="/libs/jquery-appear/jquery.appear.min.js"></script>
<script type="text/javascript" src="/libs/jquery-countto/jquery.countTo.min.js"></script>
<script type="text/javascript" src="/libs/direction/js/jquery.hoverdir.js"></script>
<script type="text/javascript" src="/libs/direction/js/modernizr.custom.97074.js"></script>
<script type="text/javascript" src="/libs/isotope/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="/libs/isotope/fit-columns.js"></script>
<script type="text/javascript" src="/libs/isotope/isotope-docs.min.js"></script>
<script type="text/javascript" src="/libs/mansory/mansory.js"></script>
<script type="text/javascript" src="/libs/prettyphoto-master/js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="/libs/slick-sider/slick.min.js"></script>
<script type="text/javascript" src="/libs/countdown-timer/js/jquery.final-countdown.min.js"></script>
<script type="text/javascript" src="/libs/countdown-timer/js/kinetic.js"></script>
<script type="text/javascript" src="/libs/owl.carousel.min/owl.carousel.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>